# Generated by Django 4.2 on 2023-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='key link')),
                ('name', models.CharField(max_length=120, verbose_name='Red social')),
                ('url', models.CharField(blank=True, max_length=350, null=True, verbose_name='Enlace')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created'], 'verbose_name': 'Acerca de', 'verbose_name_plural': 'Acerca de Nosotros'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='about',
            name='key',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='url',
        ),
        migrations.AddField(
            model_name='about',
            name='descriptions',
            field=models.CharField(max_length=350, null=True, verbose_name='Descripción'),
        ),
    ]
